### PR TITLE
Plugin Tweaks

### PR DESCRIPTION
**Pull request by benjholla**
Support for Get Simple CMS, some overal formatting/code style tweaks/error handeling, updates to the Drupal plugin

### CODE REVIEW

**Comment by sullivanmatt** [comment]
plugins/drupal.js
Line 24:
if(pageContent.indexOf('Log out ') != -1){

But in line 17 you mention that it's actually theme dependent... so wouldn't line 24 need to check for all three variations?

**Comment by benjholla** [comment]
Well, I think they are all actually theme dependent.  I added "logout" as a shot in the dark guess.  If the page has "logout" on it, its a pretty good guess that you are logged in...however I don't have an example to try that with its just a another variation of "Log Out".  

The second "Log Out" (without the space trailing) grabs it from the top bar overlay which actually might not be theme dependent, but I don't know that much about Drupal to be sure.

**Comment by benjholla** [comment]
Also, I'm not sure where your "Log out " came from.  I was just guessing
that was a theme dependent thing since I didn't see on my installation of
drupal with a custom theme.

~Ben

**Comment by sullivanmatt** [comment]
When logged in as admin on a Drupal 6 installation at Krell and ISU, specifically from the admin bar that appears.  But I agree, your method allows for more likely detection of a valid session, even if the username can't reliably be extracted.

**Comment by benjholla** [comment]
The "Log Out" (without space) keys off this admin bar seen in the top of
the image.  Just a quick survey showed it on a few different Drupal
Installations, so that why I guessed it was theme independent (but I really
wasn't sure).

http://www.portal.hrpr.com/files/images/drupal701.png

~Ben

**Pull request merged**
